// ============================================================
// Shared category classification system
// ============================================================

// ---------------------------------------------------------------------------
// Category → Group mapping (8 top-level groups)
// ---------------------------------------------------------------------------

export const CATEGORY_GROUP: Record<string, string> = {
  // DeFi
  DeFi: "DeFi",
  Dexes: "DeFi",
  Dexs: "DeFi", // actual DefiLlama API spelling
  DEX: "DeFi",
  Lending: "DeFi",
  Yield: "DeFi",
  "Yield Aggregator": "DeFi",
  "Liquid Staking": "DeFi",
  Derivatives: "DeFi",
  Perpetuals: "DeFi",
  Bridge: "DeFi",
  CDP: "DeFi",
  "CDP Manager": "DeFi",
  Options: "DeFi",
  "Options Vault": "DeFi",
  Insurance: "DeFi",
  Liquidations: "DeFi",
  "Leveraged Farming": "DeFi",
  "DEX Aggregator": "DeFi",
  Synthetics: "DeFi",
  Indexes: "DeFi",
  "Reserve Currency": "DeFi",
  "Algo-Stables": "DeFi",
  "NFT Fi": "DeFi",
  "Liquid Restaking": "DeFi",
  Restaking: "DeFi",
  RWA: "DeFi",
  MEV: "DeFi",
  "Liquidity Manager": "DeFi",
  "Liquidity manager": "DeFi", // case variant from API
  Farm: "DeFi",
  "Leveraged Yield": "DeFi",
  "Uncollateralized Lending": "DeFi",
  "Flash Loans": "DeFi",
  AMM: "DeFi",
  "Margin Trading": "DeFi",
  "Borrowing Lending": "DeFi",
  SoFi: "DeFi",
  "Structured Products": "DeFi",
  "Staking Pool": "DeFi",
  "Cross Chain": "DeFi",
  "Decentralized Stablecoin": "DeFi",
  "Prediction Market": "DeFi",
  "Leveraged Lending": "DeFi",
  "NFT Lending": "DeFi",
  Staking: "DeFi",
  "Liquid Staking Governance": "DeFi",
  "Basis Trading": "DeFi",
  "Leveraged Staking": "DeFi",
  "Concentrated Liquidity Manager": "DeFi",
  // DeFi — additional DefiLlama categories
  "Bridge Aggregator": "DeFi",
  "Governance Incentives": "DeFi",
  "Onchain Capital Allocator": "DeFi",
  "Private Investment Platform": "DeFi",
  "RWA Lending": "DeFi",
  "Restaked BTC": "DeFi",
  "Token Locker": "DeFi",
  "Volume Boosting": "DeFi",
  "Yield Lottery": "DeFi",
  CeDeFi: "DeFi",

  // Stablecoins
  Stablecoins: "Stablecoins",
  Stablecoin: "Stablecoins",
  "Stablecoin Issuer": "Stablecoins",
  "Dual-Token Stablecoin": "Stablecoins",

  // Exchanges
  Exchanges: "Exchanges",
  CEX: "Exchanges",
  "OTC Marketplace": "Exchanges",

  // Blockchains
  Blockchains: "Blockchains",
  Chain: "Blockchains",
  EVM: "Blockchains",
  "EVM Compatible": "Blockchains",
  Rollup: "Blockchains",
  Parachain: "Blockchains",
  Cosmos: "Blockchains",
  Sidechain: "Blockchains",
  Subnet: "Blockchains",
  L1: "Blockchains",
  L2: "Blockchains",
  Blockchain: "Blockchains",
  "Modular Blockchain": "Blockchains",
  "Bitcoin Sidechain": "Blockchains",
  "Optimistic Rollup": "Blockchains",
  "ZK Rollup": "Blockchains",
  Validium: "Blockchains",
  DA: "Blockchains",
  Appchain: "Blockchains",
  "Move VM": "Blockchains",
  "Anchor BTC": "Blockchains",
  "Decentralized BTC": "Blockchains",

  // Consumer
  Consumer: "Consumer",
  NFT: "Consumer",
  "NFT Marketplace": "Consumer",
  Gaming: "Consumer",
  Social: "Consumer",
  Launchpad: "Consumer",
  SocialFi: "Consumer",
  "Fan Token": "Consumer",
  Gambling: "Consumer",
  Identity: "Consumer",
  Music: "Consumer",
  Metaverse: "Consumer",
  "Play-To-Earn": "Consumer",
  "Move-To-Earn": "Consumer",
  Creator: "Consumer",
  Wallet: "Consumer",
  Wallets: "Consumer",
  Payment: "Consumer",
  Payments: "Consumer",
  Meme: "Consumer",
  // Consumer — additional DefiLlama categories
  "Coins Tracker": "Consumer",
  "Crypto Card Issuer": "Consumer",
  Domains: "Consumer",
  Interface: "Consumer",
  "Luck Games": "Consumer",
  "NFT Automated Strategies": "Consumer",
  "NFT Launchpad": "Consumer",
  "Physical TCG": "Consumer",
  "Portfolio Tracker": "Consumer",
  "Telegram Bot": "Consumer",
  "Trading App": "Consumer",

  // DePIN
  DePIN: "DePIN",
  Compute: "DePIN",
  Storage: "DePIN",
  IoT: "DePIN",
  DeWi: "DePIN",
  AI: "DePIN",
  GPU: "DePIN",
  // DePIN — additional DefiLlama categories
  "AI Agents": "DePIN",
  "Decentralized AI": "DePIN",
  "Gamified Mining": "DePIN",
  "Mining Pools": "DePIN",
  "Video Infrastructure": "DePIN",

  // Infrastructure
  Middleware: "Infrastructure",
  Oracle: "Infrastructure",
  Data: "Infrastructure",
  Infrastructure: "Infrastructure",
  Interoperability: "Infrastructure",
  Privacy: "Infrastructure",
  Automation: "Infrastructure",
  Relayer: "Infrastructure",
  RPC: "Infrastructure",
  API: "Infrastructure",
  Analytics: "Infrastructure",
  Indexer: "Infrastructure",
  // Infrastructure — additional DefiLlama categories
  "Block Builders": "Infrastructure",
  "DAO Service Provider": "Infrastructure",
  "Developer Tools": "Infrastructure",
  "Risk Curators": "Infrastructure",
  "Security Extension": "Infrastructure",
  Services: "Infrastructure",

  // Other
  Other: "Other",
};

// ---------------------------------------------------------------------------
// Protocol slug → category overrides for protocols with null categories
// Many top fee-generating protocols on DefiLlama have null categories.
// ---------------------------------------------------------------------------

export const PROTOCOL_CATEGORY_OVERRIDES: Record<string, string> = {
  // ── DEXes / AMMs ──
  "pancakeswap": "Dexs",
  "pancakeswap-amm": "Dexs",
  "pancakeswap-amm-v3": "Dexs",
  "raydium": "Dexs",
  "raydium-amm": "Dexs",
  "raydium-cpmm": "Dexs",
  "orca": "Dexs",
  "trader-joe": "Dexs",
  "trader-joe-v2.1": "Dexs",
  "sushiswap": "Dexs",
  "camelot": "Dexs",
  "camelot-v3": "Dexs",
  "velodrome": "Dexs",
  "aerodrome": "Dexs",
  "thena": "Dexs",
  "balancer": "Dexs",
  "balancer-v2": "Dexs",
  "jupiter-aggregator": "DEX Aggregator",
  "1inch-network": "DEX Aggregator",
  "paraswap": "DEX Aggregator",
  "0x-protocol": "DEX Aggregator",
  "dodo": "Dexs",
  "maverick-protocol": "Dexs",
  "ambient-finance": "Dexs",
  "meteora": "Dexs",
  "pumpswap": "Dexs",
  "pumpswap-amm": "Dexs",
  "curve-finance": "Dexs",
  "curve": "Dexs",
  "curve-dex": "Dexs",
  "kyberswap": "DEX Aggregator",
  "openocean": "DEX Aggregator",
  "odos": "DEX Aggregator",
  "cow-protocol": "DEX Aggregator",
  "cowswap": "DEX Aggregator",
  "bebop": "DEX Aggregator",
  "hashflow": "Dexs",
  "lifinity": "Dexs",
  "phoenix": "Dexs",
  "cetus": "Dexs",
  "turbos-finance": "Dexs",
  "aftermath-finance": "Dexs",
  "deepbook": "Dexs",
  "thruster": "Dexs",
  "shadedex": "Dexs",
  "baseswap": "Dexs",
  "swapblast": "Dexs",
  "syncswap": "Dexs",
  "spacefi": "Dexs",
  "wagmi": "Dexs",
  "kim-exchange": "Dexs",
  "nile-exchange": "Dexs",
  "clober": "Dexs",
  "ekubo": "Dexs",
  "jediswap": "Dexs",
  "10kswap": "Dexs",
  "myswap": "Dexs",
  "avnu": "DEX Aggregator",
  "fibrous-finance": "DEX Aggregator",

  // ── Perps / Derivatives ──
  "hyperliquid": "Perpetuals",
  "gmx": "Perpetuals",
  "gmx-v2": "Perpetuals",
  "dydx": "Perpetuals",
  "dydx-v4": "Perpetuals",
  "drift-protocol": "Perpetuals",
  "jupiter-perpetual-exchange": "Perpetuals",
  "vertex-protocol": "Perpetuals",
  "kwenta": "Perpetuals",
  "gains-network": "Perpetuals",
  "synthetix": "Derivatives",
  "polymarket": "Prediction Market",
  "azuro": "Prediction Market",
  "aevo": "Derivatives",
  "aevo-exchange": "Derivatives",
  "rabbitx": "Perpetuals",
  "bluefin": "Perpetuals",
  "zeta-markets": "Perpetuals",
  "mux-protocol": "Perpetuals",
  "perennial": "Perpetuals",
  "hmx": "Perpetuals",
  "apex-protocol": "Perpetuals",
  "kiloex": "Perpetuals",
  "holdstation": "Perpetuals",
  "orderly-network": "Perpetuals",
  "kine-finance": "Perpetuals",
  "level-finance": "Perpetuals",
  "unidex": "Perpetuals",
  "lyra-finance": "Options",
  "predy-finance": "Derivatives",
  "flash-trade": "Perpetuals",
  "drift": "Perpetuals",

  // ── Wallets / Trading Bots ──
  "metamask": "Wallet",
  "metamask-swap": "Wallet",
  "phantom": "Wallet",
  "phantom-swap": "Wallet",
  "phantom-wallet": "Wallet",
  "rabby-swap": "Wallet",
  "coinbase-wallet": "Wallet",
  "trust-wallet-swap": "Wallet",
  "banana-gun": "Wallet",
  "maestro": "Wallet",
  "photon": "Wallet",
  "bonkbot": "Wallet",
  "trojan": "Wallet",
  "axiom": "Wallet",
  "bull-x": "Wallet",
  "bullx": "Wallet",
  "gmgn": "Wallet",
  "nova": "Wallet",
  "sol-trading-bot": "Wallet",
  "bloom": "Wallet",
  "defined": "Wallet",
  "bifrost-wallet": "Wallet",
  "okx-wallet": "Wallet",
  "bitget-wallet": "Wallet",

  // ── Liquid Staking / Restaking / MEV ──
  "jito": "MEV",
  "jito-tips": "MEV",
  "lido": "Liquid Staking",
  "rocket-pool": "Liquid Staking",
  "eigenlayer": "Restaking",
  "eigenpie": "Liquid Restaking",
  "marinade-finance": "Liquid Staking",
  "coinbase-wrapped-staked-eth": "Liquid Staking",
  "ether.fi": "Liquid Restaking",
  "etherfi": "Liquid Restaking",
  "ether.fi-liquid": "Liquid Restaking",
  "ether.fi-stake": "Liquid Restaking",
  "renzo": "Liquid Restaking",
  "puffer-finance": "Liquid Restaking",
  "kelp-dao": "Liquid Restaking",
  "swell": "Liquid Restaking",
  "swell-liquid-staking": "Liquid Staking",
  "bedrock": "Liquid Restaking",
  "symbiotic": "Restaking",
  "babylon": "Restaking",
  "stakestone": "Liquid Staking",
  "stader": "Liquid Staking",
  "stader-labs": "Liquid Staking",
  "ankr-staking": "Liquid Staking",
  "mantle-staked-eth": "Liquid Staking",
  "binance-staked-eth": "Liquid Staking",
  "frax-ether": "Liquid Staking",
  "titan-builder": "MEV",
  "rsync-builder": "MEV",
  "flashbots": "MEV",
  "beaverbuild": "MEV",
  "blocknative": "MEV",
  "manifold-finance": "MEV",
  "eden-network": "MEV",
  "jito-mev": "MEV",

  // ── Lending ──
  "aave": "Lending",
  "aave-v2": "Lending",
  "aave-v3": "Lending",
  "compound": "Lending",
  "compound-v3": "Lending",
  "morpho": "Lending",
  "morpho-blue": "Lending",
  "spark": "Lending",
  "spark-lending": "Lending",
  "spark-liquidity-layer": "Lending",
  "spark-lend": "Lending",
  "venus": "Lending",
  "benqi-lending": "Lending",
  "kamino-lending": "Lending",
  "kamino": "Lending",
  "euler": "Lending",
  "euler-v2": "Lending",
  "fluid": "Lending",
  "fluid-lending": "Lending",
  "moonwell": "Lending",
  "radiant-capital": "Lending",
  "radiant-v2": "Lending",
  "silo-finance": "Lending",
  "silo-v2": "Lending",
  "ajna": "Lending",
  "notional-finance": "Lending",
  "goldfinch": "Uncollateralized Lending",
  "maple-finance": "Uncollateralized Lending",
  "maple": "Uncollateralized Lending",
  "clearpool": "Uncollateralized Lending",
  "centrifuge": "RWA",
  "truefi": "Uncollateralized Lending",
  "iron-bank": "Lending",
  "uwu-lend": "Lending",
  "zerolend": "Lending",
  "init-capital": "Lending",
  "marginfi": "Lending",
  "solend": "Lending",
  "save": "Lending",

  // ── Stablecoins / CDP ──
  "maker": "CDP",
  "makerdao": "CDP",
  "sky": "CDP",
  "sky-lending": "CDP",
  "sky-ecosystem": "CDP",
  "tether": "Stablecoins",
  "circle": "Stablecoins",
  "usdc": "Stablecoins",
  "circle-usdc": "Stablecoins",
  "dai": "Stablecoins",
  "ethena": "Stablecoins",
  "ethena-labs": "Stablecoins",
  "frax": "Stablecoins",
  "rai": "CDP",
  "liquity": "CDP",
  "liquity-v2": "CDP",
  "prisma-finance": "CDP",
  "usual": "Stablecoins",
  "usual-money": "Stablecoins",
  "first-digital-usd": "Stablecoins",
  "paypal-usd": "Stablecoins",
  "mountain-protocol": "Stablecoins",
  "agora": "Stablecoins",
  "ondo-finance": "RWA",
  "ondo": "RWA",
  "steakhouse-financial": "RWA",
  "steakhouse": "RWA",
  "backed-finance": "RWA",
  "hashnote": "RWA",
  "superstate": "RWA",

  // ── Bridges / Cross-chain ──
  "across-protocol": "Bridge",
  "stargate": "Bridge",
  "wormhole": "Bridge",
  "layerzero": "Bridge",
  "hop-protocol": "Bridge",
  "synapse": "Bridge",
  "circle-cctp": "Bridge",
  "squid": "Bridge",
  "socket": "Bridge",
  "debridge": "Bridge",
  "relay": "Bridge",
  "celer-cbridge": "Bridge",
  "multichain": "Bridge",
  "axelar": "Bridge",
  "orbiter-finance": "Bridge",
  "connext": "Bridge",
  "near-intents": "Bridge",
  "near-intent": "Bridge",
  "allbridge": "Bridge",
  "meson": "Bridge",
  "symbiosis": "Bridge",
  "li-fi": "Bridge",

  // ── Consumer / Launchpads ──
  "pump.fun": "Launchpad",
  "pumpfun": "Launchpad",
  "pump-fun": "Launchpad",
  "friend.tech": "SocialFi",
  "friendtech": "SocialFi",
  "opensea": "NFT Marketplace",
  "blur": "NFT Marketplace",
  "magic-eden": "NFT Marketplace",
  "rarible": "NFT Marketplace",
  "x2y2": "NFT Marketplace",
  "farcaster": "SocialFi",
  "lens-protocol": "SocialFi",
  "stepn": "Move-To-Earn",
  "axie-infinity": "Gaming",
  "fomo": "Launchpad",
  "antfun": "Launchpad",
  "ant-fun": "Launchpad",
  "moonshot": "Launchpad",
  "four.meme": "Launchpad",
  "clanker": "Launchpad",
  "virtuals-protocol": "AI",
  "virtuals": "AI",
  "virtual-protocol": "AI",
  "courtyard": "NFT Marketplace",
  "courtyard.io": "NFT Marketplace",
  "zora": "NFT Marketplace",
  "foundation": "NFT Marketplace",
  "sudoswap": "NFT Marketplace",
  "tensor": "NFT Marketplace",
  "topaz": "NFT Marketplace",
  "tokenworks": "Launchpad",
  "token-works": "Launchpad",

  // ── Yield / Aggregators ──
  "pendle": "Yield",
  "yearn-finance": "Yield Aggregator",
  "yearn": "Yield Aggregator",
  "beefy": "Yield Aggregator",
  "beefy-finance": "Yield Aggregator",
  "sommelier": "Yield",
  "harvest-finance": "Yield Aggregator",
  "convex-finance": "Yield",
  "stakedao": "Yield",
  "concentrator": "Yield Aggregator",
  "gearbox": "Leveraged Yield",
  "instadapp": "Yield",
  "mellow-protocol": "Yield",

  // ── Liquidity Managers ──
  "gauntlet": "Liquidity Manager",
  "arrakis-finance": "Liquidity Manager",
  "gamma-strategies": "Liquidity Manager",
  "charm-finance": "Liquidity Manager",

  // ── Infrastructure / Oracles ──
  "chainlink": "Oracle",
  "pyth-network": "Oracle",
  "the-graph": "Indexer",
  "filecoin": "Storage",
  "arweave": "Storage",
  "render": "Compute",
  "akash-network": "Compute",
  "helium": "DeWi",
  "hivemapper": "DePIN",
  "worldcoin": "Identity",
  "ens": "Identity",
  "ens-domains": "Identity",
  "unstoppable-domains": "Identity",
  "space-id": "Identity",
  "galxe": "Identity",
  "bittensor": "AI",
  "io-net": "Compute",
  "nosana": "Compute",
  "livepeer": "Compute",
  "grass": "DePIN",
  "ore-protocol": "DePIN",
  "ore": "DePIN",

  // ── Exchanges ──
  "backpack-exchange": "CEX",
  "backpack": "CEX",
  "bitget": "CEX",
  "bybit": "CEX",
  "binance": "CEX",
  "okx": "CEX",
  "coinbase": "CEX",
  "kraken": "CEX",
  "htx": "CEX",
  "crypto-com": "CEX",
  "kucoin": "CEX",
  "gate-io": "CEX",
  "mexc": "CEX",

  // ── Chains (parent protocols sometimes have null category) ──
  "ethereum": "Chain",
  "bitcoin": "Chain",
  "solana": "Chain",
  "avalanche": "Chain",
  "polygon": "Chain",
  "arbitrum": "Chain",
  "optimism": "Chain",
  "base": "Chain",
  "bnb-chain": "Chain",
  "bsc": "Chain",
  "tron": "Chain",
  "fantom": "Chain",
  "sui": "Chain",
  "aptos": "Chain",
  "near": "Chain",
  "sei": "Chain",
  "mantle": "Chain",
  "scroll": "Chain",
  "linea": "Chain",
  "zksync-era": "Chain",
  "zksync": "Chain",
  "starknet": "Chain",
  "blast": "Chain",
  "mode": "Chain",
  "manta-pacific": "Chain",
  "merlin-chain": "Chain",
  "celo": "Chain",
  "gnosis": "Chain",
  "moonbeam": "Chain",
  "cronos": "Chain",
  "kava": "Chain",
  "hedera": "Chain",
  "cardano": "Chain",
  "polkadot": "Chain",
  "cosmos-hub": "Chain",
  "injective": "Chain",
  "osmosis": "Chain",
  "ton": "Chain",
  "monad": "Chain",
  "berachain": "Chain",
  "sonic": "Chain",
  "sonic-labs": "Chain",
  "abstract": "Chain",
  "megaeth": "Chain",
  "hyperliquid-l1": "Chain",
  "taiko": "Chain",
  "zkfair": "Chain",
  "immutable-x": "Chain",
  "ronin": "Chain",
  "wemix": "Chain",
  "klaytn": "Chain",
  "moonriver": "Chain",
  "aurora": "Chain",
  "boba-network": "Chain",
  "metis": "Chain",
  "harmony": "Chain",
  "canto": "Chain",
  "core-dao": "Chain",
  "flare": "Chain",
  "rootstock": "Chain",
  "bob": "Chain",
  "world-chain": "Chain",
  "ink": "Chain",
  "unichain": "Chain",
  "treasure": "Chain",
  "polygon-zkevm": "Chain",
  "zircuit": "Chain",
  "morph": "Chain",
  "fraxtal": "Chain",
  "redstone": "Chain",

  // ── Additional protocol overrides (from "Other" cleanup) ──
  "padre": "Launchpad",
  "collector-crypt": "NFT Marketplace",
  "collectorcrypt": "NFT Marketplace",
  "catfee": "Launchpad",
  "cat-fee": "Launchpad",
  "m0": "Stablecoins",
  "m0-foundation": "Stablecoins",
  "bankr": "Wallet",
  "base-app": "Chain",
  "base-name-service": "Identity",
  "phantom-perps": "Perpetuals",
  "dex-screener": "Wallet",
  "dexscreener": "Wallet",
  "spark-liquidity": "Lending",

  // ── More protocols commonly in "Other" ──
  "matcha": "DEX Aggregator",
  "zeroex": "DEX Aggregator",
  "firebird-finance": "DEX Aggregator",
  "rubic": "DEX Aggregator",
  "rango": "DEX Aggregator",
  "jumper-exchange": "DEX Aggregator",
  "jupiter-dca": "DEX Aggregator",
  "jupiter-limit": "DEX Aggregator",
  "jupiter-perpetual": "Perpetuals",
  "jupiter-perps": "Perpetuals",
  "aldrin": "Dexs",
  "saros": "Dexs",

  // ── Prediction markets / Betting ──
  "overtime-markets": "Prediction Market",
  "thales": "Prediction Market",
  "sx-bet": "Prediction Market",

  // ── Insurance ──
  "nexus-mutual": "Insurance",
  "insurace": "Insurance",

  // ── Payments / Transfers ──
  "gnosis-pay": "Payments",
  "sling": "Payments",
  "utila": "Payments",

  // ── Derivatives / Structured Products ──
  "ribbon-finance": "Options",
  "opyn": "Options",
  "hegic": "Options",
  "dopex": "Options",
  "derive": "Options",
  "thetanuts-finance": "Options",
  "buffer-finance": "Options",
  "typus-finance": "Options",

  // ── Privacy ──
  "railgun": "Privacy",
  "tornado-cash": "Privacy",

  // ── Liquid Staking additional ──
  "sanctum": "Liquid Staking",
  "benqi-staked-avax": "Liquid Staking",
  "origin-ether": "Liquid Staking",
  "dinero-pxeth": "Liquid Restaking",

  // ── RWA additional ──
  "securitize": "RWA",
  "swarm": "RWA",
  "realio": "RWA",
  "propchain": "RWA",
  "credix": "RWA",
  "parcl": "RWA",

  // ── Gaming / Metaverse ──
  "immutable": "Gaming",
  "immutable-passport": "Gaming",
  "gala-games": "Gaming",
  "yield-guild-games": "Gaming",
  "illuvium": "Gaming",
  "gods-unchained": "Gaming",
  "pixels": "Gaming",
  "star-atlas": "Gaming",
  "parallel": "Gaming",

  // ── Social / Content ──
  "mirror": "SocialFi",
  "paragraph": "SocialFi",
  "drakula": "SocialFi",
  "hey": "SocialFi",
  "orb": "SocialFi",

  // ── AI / Data ──
  "fetch.ai": "AI",
  "singularitynet": "AI",
  "ocean-protocol": "AI",
  "giza": "AI",
  "pond": "AI",
  "allora": "AI",
  "morpheus": "AI",
  "cookie": "AI",
  "cookie-fun": "AI",
  "cookie3": "AI",
  "kaito": "AI",
  "nillion": "AI",
  "ritual": "AI",
  "modulus-labs": "AI",
  "ora": "AI",
  "sahara-ai": "AI",
  "prime-intellect": "AI",
  "sentient": "AI",
  "nous-research": "AI",
  "eliza": "AI",
  "ai16z": "AI",
  "griffain": "AI",
  "wayfinder": "AI",
};

// ---------------------------------------------------------------------------
// Category → Color mapping (WSJ-style)
// ---------------------------------------------------------------------------

export const GROUP_COLORS: Record<string, string> = {
  DeFi: "#3b82f6",
  Stablecoins: "#10b981",
  Exchanges: "#8b5cf6",
  Blockchains: "#f59e0b",
  Consumer: "#ef4444",
  DePIN: "#ec4899",
  Infrastructure: "#6366f1",
  Other: "#94a3b8",
};

export const CATEGORY_COLORS: Record<string, string> = (() => {
  // Generate from CATEGORY_GROUP → GROUP_COLORS mapping
  const colors: Record<string, string> = {};
  for (const [cat, group] of Object.entries(CATEGORY_GROUP)) {
    colors[cat] = GROUP_COLORS[group] || "#94a3b8";
  }
  return colors;
})();

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

// Case-insensitive lookup built from CATEGORY_GROUP
const CATEGORY_GROUP_CI = new Map<string, string>();
for (const [k, v] of Object.entries(CATEGORY_GROUP)) {
  CATEGORY_GROUP_CI.set(k.toLowerCase(), v);
}

/**
 * Get the top-level group for a raw category string.
 * Optionally pass a slug to check PROTOCOL_CATEGORY_OVERRIDES.
 *
 * Priority: slug override (manually curated) → direct category → case-insensitive → "Other"
 */
export function getCategoryGroup(category: string, slug?: string): string {
  // 1. Slug-based override (highest priority — manually curated)
  if (slug) {
    const override = PROTOCOL_CATEGORY_OVERRIDES[slug.toLowerCase()];
    if (override) {
      const overrideGroup = CATEGORY_GROUP[override];
      if (overrideGroup) return overrideGroup;
    }
  }

  // 2. Direct lookup
  const direct = CATEGORY_GROUP[category];
  if (direct) return direct;

  // 3. Case-insensitive lookup
  const ci = CATEGORY_GROUP_CI.get(category.toLowerCase());
  if (ci) return ci;

  return "Other";
}

export function getCategoryColor(category: string, slug?: string): string {
  const group = getCategoryGroup(category, slug);
  return GROUP_COLORS[group] || "#94a3b8";
}

// CoinGecko category keywords → group mapping
const CG_CATEGORY_KEYWORDS: [RegExp, string, string][] = [
  [/\b(layer-1|smart-contract|proof-of-work|proof-of-stake)\b/i, "Blockchains", "L1"],
  [/\b(layer-2|rollup|optimistic|zk-rollup|scaling)\b/i, "Blockchains", "L2"],
  [/\b(decentral.*(exchange|swap)|dex|amm)\b/i, "DeFi", "Dexes"],
  [/\b(lend|borrow)\b/i, "DeFi", "Lending"],
  [/\b(liquid.staking)\b/i, "DeFi", "Liquid Staking"],
  [/\b(restaking)\b/i, "DeFi", "Restaking"],
  [/\b(yield|farm)\b/i, "DeFi", "Yield"],
  [/\b(deriv|perp|future|option)\b/i, "DeFi", "Derivatives"],
  [/\b(bridge|cross.chain|interop)\b/i, "DeFi", "Bridge"],
  [/\b(stablecoin)\b/i, "Stablecoins", "Stablecoins"],
  [/\b(nft|collectible)\b/i, "Consumer", "NFT"],
  [/\b(gaming|game|play.to.earn|metaverse)\b/i, "Consumer", "Gaming"],
  [/\b(social|fan.token)\b/i, "Consumer", "Social"],
  [/\b(predict|gambl|bet)\b/i, "Consumer", "Prediction Market"],
  [/\b(oracle|data)\b/i, "Infrastructure", "Oracle"],
  [/\b(storage|file)\b/i, "DePIN", "Storage"],
  [/\b(compute|gpu|render)\b/i, "DePIN", "Compute"],
  [/\b(iot|wireless|depin)\b/i, "DePIN", "DePIN"],
  [/\b(privacy|mixer)\b/i, "Infrastructure", "Privacy"],
  [/\b(exchange|cex)\b/i, "Exchanges", "CEX"],
  [/\b(wallet|payment)\b/i, "Consumer", "Wallet"],
  [/\b(meme)\b/i, "Consumer", "Meme"],
  [/\b(governance|dao)\b/i, "DeFi", "DeFi"],
  [/\b(insurance)\b/i, "DeFi", "Insurance"],
  [/\b(identity|did)\b/i, "Consumer", "Identity"],
];

// Name-based keyword heuristics as last resort
const NAME_KEYWORDS: [RegExp, string, string][] = [
  [/swap|dex|amm/i, "DeFi", "Dexes"],
  [/lend|borrow|credit/i, "DeFi", "Lending"],
  [/stake|staking/i, "DeFi", "Liquid Staking"],
  [/bridge/i, "DeFi", "Bridge"],
  [/\bchain\b|\bl1\b|\bl2\b|rollup/i, "Blockchains", "L1"],
  [/nft|art|collect/i, "Consumer", "NFT"],
  [/game|play|quest/i, "Consumer", "Gaming"],
  [/\bpay\b|wallet/i, "Consumer", "Wallet"],
  [/stable/i, "Stablecoins", "Stablecoins"],
  [/oracle|feed/i, "Infrastructure", "Oracle"],
  [/render|compute|gpu/i, "DePIN", "Compute"],
  [/storage|file/i, "DePIN", "Storage"],
  [/meme|doge|shib|inu|pepe|bonk|cat|dog|frog/i, "Consumer", "Meme"],
  [/\bai\b|artificial|intelligence|agent/i, "DePIN", "AI"],
  [/exchange|cex/i, "Exchanges", "CEX"],
];

/**
 * Auto-categorize a token/protocol using available signals.
 *
 * Fallback chain:
 * 1. DefiLlama category (via CATEGORY_GROUP)
 * 2. CoinGecko categories (keyword matching)
 * 3. Name-based heuristics
 * 4. "Other" / "Uncategorized"
 */
export function categorizeToken(
  defiLlamaCategory: string | null | undefined,
  coinGeckoCategories: string[] | null | undefined,
  name: string,
  coinGeckoId?: string | null,
): { categoryGroup: string; subcategory: string } {
  // 0. Direct CoinGecko ID lookup (most reliable)
  if (coinGeckoId) {
    const sector = CG_TOKEN_SECTOR[coinGeckoId];
    if (sector) return { categoryGroup: sector, subcategory: sector };
  }

  // 1. DefiLlama category
  if (defiLlamaCategory && CATEGORY_GROUP[defiLlamaCategory]) {
    return {
      categoryGroup: CATEGORY_GROUP[defiLlamaCategory],
      subcategory: defiLlamaCategory,
    };
  }

  // 2. CoinGecko categories
  if (coinGeckoCategories?.length) {
    const joined = coinGeckoCategories.join(" ");
    for (const [pattern, group, sub] of CG_CATEGORY_KEYWORDS) {
      if (pattern.test(joined)) {
        return { categoryGroup: group, subcategory: sub };
      }
    }
  }

  // 3. Name heuristics
  for (const [pattern, group, sub] of NAME_KEYWORDS) {
    if (pattern.test(name)) {
      return { categoryGroup: group, subcategory: sub };
    }
  }

  // 4. Fallback
  return { categoryGroup: "Other", subcategory: "Other" };
}

// ---------------------------------------------------------------------------
// CoinGecko category ID → sector mapping
// Used to aggregate /coins/categories market cap data by sector.
// Categories that are marketing labels (e.g. "made-in-usa") are excluded.
// ---------------------------------------------------------------------------

export const CG_CATEGORY_SECTOR: Record<string, string> = {
  // Blockchains / L1 / L2
  "smart-contract-platform": "Blockchains",
  "layer-1": "Blockchains",
  "proof-of-work-pow": "Blockchains",
  "proof-of-stake-pos": "Blockchains",
  "layer-2": "Blockchains",
  "layer-0-l0": "Blockchains",
  "zero-knowledge-zk": "Blockchains",
  "rollup": "Blockchains",
  "sidechain": "Blockchains",
  "bitcoin-fork": "Blockchains",
  "directed-acyclic-graph-dag": "Blockchains",
  "privacy-coins": "Blockchains",
  "privacy-blockchain": "Blockchains",
  "bitcoin-layer-2": "Blockchains",
  "data-availability": "Blockchains",
  "quantum-resistant": "Blockchains",
  "modular-blockchain": "Blockchains",
  "cosmos-ecosystem": "Blockchains",
  "polkadot-ecosystem": "Blockchains",
  "avalanche-ecosystem": "Blockchains",
  "near-protocol-ecosystem": "Blockchains",
  "solana-ecosystem": "Blockchains",
  "ethereum-ecosystem": "Blockchains",
  "masternodes": "Blockchains",
  "superchain-ecosystem": "Blockchains",
  "gaming-blockchains": "Blockchains",
  "move-ecosystem": "Blockchains",
  "chain-abstraction": "Blockchains",
  "appchain": "Blockchains",

  // DeFi
  "decentralized-finance-defi": "DeFi",
  "decentralized-exchange": "DeFi",
  "automated-market-maker-amm": "DeFi",
  "decentralized-perpetuals": "DeFi",
  "decentralized-derivatives": "DeFi",
  "decentralized-options": "DeFi",
  "lending-borrowing": "DeFi",
  "yield-farming": "DeFi",
  "yield-bearing-tokens": "DeFi",
  "liquid-staking": "DeFi",
  "liquid-staking-governance": "DeFi",
  "liquid-restaking-tokens": "DeFi",
  "cross-chain-communication": "DeFi",
  "governance": "DeFi",
  "insurance": "DeFi",
  "prediction-markets": "DeFi",
  "real-world-assets-rwa": "DeFi",
  "rwa-protocol": "DeFi",
  "tokenized-products": "DeFi",
  "tokenized-private-credit": "DeFi",
  "tokenized-commodities": "DeFi",
  "tokenized-gold": "DeFi",
  "tokenized-t-bills": "DeFi",
  "defi-pulse-index-dpi": "DeFi",
  "bridge-governance-tokens": "DeFi",

  // Stablecoins
  "stablecoins": "Stablecoins",
  "usd-stablecoin": "Stablecoins",
  "fiat-backed-stablecoin": "Stablecoins",
  "crypto-backed-stablecoin": "Stablecoins",
  "algorithmic-stablecoin": "Stablecoins",
  "synthetic-dollar": "Stablecoins",
  "yield-bearing-stablecoins": "Stablecoins",
  "stablecoin-issuer": "Stablecoins",
  "euro-stablecoin": "Stablecoins",

  // Exchanges
  "exchange-based-tokens": "Exchanges",
  "centralized-exchange-token-cex": "Exchanges",

  // Consumer
  "non-fungible-tokens-nft": "Consumer",
  "gaming": "Consumer",
  "play-to-earn": "Consumer",
  "gaming-utility-token": "Consumer",
  "metaverse": "Consumer",
  "socialfi": "Consumer",
  "meme-token": "Consumer",
  "dog-themed-coins": "Consumer",
  "frog-themed-coins": "Consumer",
  "cat-themed-tokens": "Consumer",
  "solana-meme-coins": "Consumer",
  "base-meme-coins": "Consumer",
  "politifi": "Consumer",
  "wallets": "Consumer",
  "payment-solutions": "Consumer",
  "launchpad": "Consumer",
  "gambling": "Consumer",
  "neobank": "Consumer",
  "identity": "Consumer",
  "fan-token": "Consumer",
  "move-to-earn": "Consumer",
  "music": "Consumer",

  // DePIN
  "depin": "DePIN",
  "storage": "DePIN",
  "artificial-intelligence": "DePIN",
  "ai-agents": "DePIN",
  "ai-framework": "DePIN",
  "ai-applications": "DePIN",
  "ai-meme-coins": "Consumer",
  "ai-agent-launchpad": "DePIN",
  "internet-of-things-iot": "DePIN",
  "cybersecurity": "DePIN",
  "mobile-mining": "DePIN",

  // Infrastructure
  "oracle": "Infrastructure",
  "analytics": "Infrastructure",
  "infrastructure": "Infrastructure",
  "privacy-infrastructure": "Infrastructure",
};

// ---------------------------------------------------------------------------
// CoinGecko token ID → sector direct mapping for top tokens.
// Avoids relying on name heuristics for the most important tokens.
// Each token appears in exactly one sector (no double-counting).
// ---------------------------------------------------------------------------

export const CG_TOKEN_SECTOR: Record<string, string> = {
  // ── Blockchains (L1, L2, sidechains, PoW forks) ──
  "bitcoin": "Blockchains",
  "ethereum": "Blockchains",
  "ripple": "Blockchains",
  "solana": "Blockchains",
  "binancecoin": "Blockchains",
  "cardano": "Blockchains",
  "tron": "Blockchains",
  "avalanche-2": "Blockchains",
  "polkadot": "Blockchains",
  "litecoin": "Blockchains",
  "stellar": "Blockchains",
  "near": "Blockchains",
  "algorand": "Blockchains",
  "cosmos": "Blockchains",
  "aptos": "Blockchains",
  "sui": "Blockchains",
  "fantom": "Blockchains",
  "hedera-hashgraph": "Blockchains",
  "arbitrum": "Blockchains",
  "optimism": "Blockchains",
  "polygon-ecosystem-token": "Blockchains",
  "matic-network": "Blockchains",
  "mantle": "Blockchains",
  "sei-network": "Blockchains",
  "celestia": "Blockchains",
  "injective-protocol": "Blockchains",
  "stacks": "Blockchains",
  "the-open-network": "Blockchains",
  "toncoin": "Blockchains",
  "kaspa": "Blockchains",
  "internet-computer": "Blockchains",
  "elrond-erd-2": "Blockchains",
  "multiversx-egld": "Blockchains",
  "vechain": "Blockchains",
  "cronos": "Blockchains",
  "celo": "Blockchains",
  "gnosis": "Blockchains",
  "zilliqa": "Blockchains",
  "harmony": "Blockchains",
  "flow-token": "Blockchains",
  "mina-protocol": "Blockchains",
  "eos": "Blockchains",
  "neo": "Blockchains",
  "iota": "Blockchains",
  "kava": "Blockchains",
  "moonbeam": "Blockchains",
  "klaytn": "Blockchains",
  "oasis-network": "Blockchains",
  "zksync": "Blockchains",
  "starknet": "Blockchains",
  "scroll": "Blockchains",
  "blast": "Blockchains",
  "mode": "Blockchains",
  "linea": "Blockchains",
  "base": "Blockchains",
  "bitcoin-cash": "Blockchains",
  "monero": "Blockchains",
  "zcash": "Blockchains",
  "dash": "Blockchains",
  "ethereum-classic": "Blockchains",
  "wrapped-bitcoin": "Blockchains",
  "staked-ether": "Blockchains",
  "weth": "Blockchains",
  "pi-network-iou": "Blockchains",
  "xdc-network": "Blockchains",
  "sonic-svm": "Blockchains",
  "sonic-3": "Blockchains",
  "berachain-bera": "Blockchains",
  "core": "Blockchains",
  "flare-networks": "Blockchains",
  "conflux-token": "Blockchains",
  "wemix-token": "Blockchains",
  "nervos-network": "Blockchains",
  "decred": "Blockchains",
  "ravencoin": "Blockchains",
  "ergo": "Blockchains",
  "kadena": "Blockchains",
  "loopring": "Blockchains",
  "skale": "Blockchains",
  "canto": "Blockchains",
  "metis-token": "Blockchains",
  "boba-network": "Blockchains",
  "lukso-token-2": "Blockchains",
  "syscoin": "Blockchains",
  "neon": "Blockchains",
  "bitcoin-cash-sv": "Blockchains",
  "qtum": "Blockchains",
  "waves": "Blockchains",
  "icon": "Blockchains",
  "lisk": "Blockchains",
  "holo": "Blockchains",
  "radix": "Blockchains",
  "terra-luna-2": "Blockchains",
  "terra-luna": "Blockchains",
  "binance-peg-ethereum": "Blockchains",
  "huobi-btc": "Blockchains",

  // ── DeFi (DEXes, lending, derivatives, bridges, liquid staking, yield) ──
  "uniswap": "DeFi",
  "aave": "DeFi",
  "lido-dao": "DeFi",
  "maker": "DeFi",
  "curve-dao-token": "DeFi",
  "compound-governance-token": "DeFi",
  "pancakeswap-token": "DeFi",
  "raydium": "DeFi",
  "jupiter-exchange-solana": "DeFi",
  "synthetix-network-token": "DeFi",
  "sushi": "DeFi",
  "balancer": "DeFi",
  "yearn-finance": "DeFi",
  "1inch": "DeFi",
  "convex-finance": "DeFi",
  "gmx": "DeFi",
  "dydx-chain": "DeFi",
  "pendle": "DeFi",
  "ondo-finance": "DeFi",
  "ethena": "DeFi",
  "morpho": "DeFi",
  "aero": "DeFi",
  "velodrome-finance": "DeFi",
  "rocket-pool": "DeFi",
  "frax-share": "DeFi",
  "ens": "DeFi",
  "osmosis": "DeFi",
  "thorchain": "DeFi",
  "joe": "DeFi",
  "drift-protocol": "DeFi",
  "kamino": "DeFi",
  "marinade": "DeFi",
  "jito-governance-token": "DeFi",
  "vertex-protocol": "DeFi",
  "ribbon-finance": "DeFi",
  "mango-markets": "DeFi",
  "radiant-capital": "DeFi",
  "benqi": "DeFi",
  "instadapp": "DeFi",
  "spell-token": "DeFi",
  "olympus": "DeFi",
  "rune": "DeFi",
  "woo-network": "DeFi",
  "maverick-protocol": "DeFi",
  "kwenta": "DeFi",
  "gains-network": "DeFi",
  "hyperliquid": "DeFi",
  "eigenlayer": "DeFi",
  "across-protocol": "DeFi",
  "stargate-finance": "DeFi",
  "wormhole": "DeFi",
  "bittensor": "DePIN",
  "sky-mavis": "Consumer",
  "mantra": "DeFi",
  "usual": "DeFi",
  "aevo-exchange": "DeFi",
  "spark": "DeFi",
  "venus-protocol": "DeFi",
  "wrapped-steth": "DeFi",
  "aerodrome-finance": "DeFi",
  "orca": "DeFi",
  "camelot-token": "DeFi",
  "thena": "DeFi",
  "baseswap": "DeFi",
  "ambient-finance": "DeFi",
  "meteora": "DeFi",
  "sky": "DeFi",

  // ── Stablecoins ──
  "tether": "Stablecoins",
  "usd-coin": "Stablecoins",
  "dai": "Stablecoins",
  "frax": "Stablecoins",
  "true-usd": "Stablecoins",
  "paxos-standard": "Stablecoins",
  "usdd": "Stablecoins",
  "first-digital-usd": "Stablecoins",
  "ethena-usde": "Stablecoins",
  "paypal-usd": "Stablecoins",
  "gemini-dollar": "Stablecoins",
  "binance-usd": "Stablecoins",
  "rai": "Stablecoins",
  "liquity-usd": "Stablecoins",
  "crvusd": "Stablecoins",
  "usual-usd": "Stablecoins",

  // ── Exchanges ──
  "crypto-com-chain": "Exchanges",
  "okb": "Exchanges",
  "kucoin-shares": "Exchanges",
  "gate-token": "Exchanges",
  "mx-token": "Exchanges",
  "leo-token": "Exchanges",
  "huobi-token": "Exchanges",
  "bitget-token": "Exchanges",
  "whitebit": "Exchanges",
  "tokenize-xchange": "Exchanges",
  "gatechain-token": "Exchanges",
  "bitmart-token": "Exchanges",
  "ftx-token": "Exchanges",

  // ── Consumer (NFT, Gaming, Meme, Social, Wallet, Prediction) ──
  "polymarket": "Consumer",
  "apecoin": "Consumer",
  "the-sandbox": "Consumer",
  "decentraland": "Consumer",
  "axie-infinity": "Consumer",
  "gala": "Consumer",
  "stepn": "Consumer",
  "immutable-x": "Consumer",
  "enjincoin": "Consumer",
  "ronin": "Consumer",
  "magic-eden": "Consumer",
  "blur-token": "Consumer",
  "farcaster": "Consumer",
  "lens-protocol": "Consumer",
  "friend-tech": "Consumer",
  "pump-fun": "Consumer",
  "dogecoin": "Consumer",
  "shiba-inu": "Consumer",
  "pepe": "Consumer",
  "bonk": "Consumer",
  "floki": "Consumer",
  "dogwifcoin": "Consumer",
  "brett": "Consumer",
  "popcat": "Consumer",
  "memecoin": "Consumer",
  "mog-coin": "Consumer",
  "book-of-meme": "Consumer",
  "cats-in-a-dogs-world": "Consumer",
  "trump": "Consumer",
  "official-trump": "Consumer",
  "pengu": "Consumer",
  "pudgy-penguins": "Consumer",
  "phantom": "Consumer",
  "fartcoin": "Consumer",
  "ai16z": "Consumer",
  "goatseus-maximus": "Consumer",
  "turbo": "Consumer",
  "neiro": "Consumer",
  "neiro-3": "Consumer",
  "moo-deng": "Consumer",
  "spx6900": "Consumer",
  "toshi-2": "Consumer",
  "peanut-the-squirrel": "Consumer",
  "chillguy": "Consumer",
  "wax": "Consumer",
  "echelon-prime": "Consumer",
  "yield-guild-games": "Consumer",
  "illuvium": "Consumer",
  "vulcan-forged": "Consumer",
  "my-neighbor-alice": "Consumer",
  "super-rare": "Consumer",
  "looksrare": "Consumer",
  "rarible": "Consumer",
  "origin-protocol": "Consumer",
  "beam-2": "Consumer",
  "saga-2": "Consumer",

  // ── DePIN (storage, compute, AI, IoT, wireless) ──
  "theta-token": "DePIN",
  "theta-fuel": "DePIN",
  "filecoin": "DePIN",
  "render-token": "DePIN",
  "arweave": "DePIN",
  "helium": "DePIN",
  "fetch-ai": "DePIN",
  "singularitynet": "DePIN",
  "ocean-protocol": "DePIN",
  "akash-network": "DePIN",
  "io-net": "DePIN",
  "worldcoin-wld": "DePIN",
  "grass": "DePIN",
  "hivemapper": "DePIN",
  "nosana": "DePIN",
  "virtual-protocol": "DePIN",
  "golem": "DePIN",
  "livepeer": "DePIN",
  "iotex": "DePIN",
  "bittorrent": "DePIN",
  "artificial-superintelligence-alliance": "DePIN",

  // ── Infrastructure (oracles, indexers, interop, analytics) ──
  "chainlink": "Infrastructure",
  "the-graph": "Infrastructure",
  "pyth-network": "Infrastructure",
  "api3": "Infrastructure",
  "band-protocol": "Infrastructure",
  "biconomy": "Infrastructure",
  "gelato": "Infrastructure",
  "ankr": "Infrastructure",
  "quant-network": "Infrastructure",
  "story-protocol-ip": "Infrastructure",
};

// Ordered group list for consistent display
export const GROUP_ORDER = [
  "DeFi",
  "Blockchains",
  "Stablecoins",
  "Exchanges",
  "Consumer",
  "DePIN",
  "Infrastructure",
  "Other",
] as const;

export const FILTER_CATEGORIES = ["All", ...GROUP_ORDER] as const;
export type FilterCategory = (typeof FILTER_CATEGORIES)[number];
